//this file is generated by program automatically,don't modify it!
#include <drogon/DrTemplate.h>
class ListBooks:public drogon::DrTemplate<ListBooks>
{
public:
	ListBooks(){};
	virtual ~ListBooks(){};
	virtual std::string genText(const drogon::DrTemplateData &) override;
};
