/**
 *
 *  BookTypes.cc
 *  DO NOT EDIT. This file is generated by drogon_ctl
 *
 */

#include "BookTypes.h"
#include <drogon/utils/Utilities.h>
#include <string>

using namespace drogon;
using namespace drogon::orm;
using namespace drogon_model::library;

const std::string BookTypes::primaryKeyName = "type_id";
const bool BookTypes::hasPrimaryKey = true;
const std::string BookTypes::tableName = "\"book_types\"";

const std::vector<typename BookTypes::MetaData> BookTypes::metaData_={
};
const std::string &BookTypes::getColumnName(size_t index) noexcept(false)
{
    assert(index < metaData_.size());
    return metaData_[index].colName_;
}
BookTypes::BookTypes(const Row &r, const ssize_t indexOffset) noexcept
{
    if(indexOffset < 0)
    {
    }
    else
    {
        size_t offset = (size_t)indexOffset;
        if(offset + 0 > r.size())
        {
            LOG_FATAL << "Invalid SQL result for this model";
            return;
        }
        size_t index;
    }

}

BookTypes::BookTypes(const Json::Value &pJson, const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 0)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
}

BookTypes::BookTypes(const Json::Value &pJson) noexcept(false)
{
}

void BookTypes::updateByMasqueradedJson(const Json::Value &pJson,
                                            const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 0)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
}

void BookTypes::updateByJson(const Json::Value &pJson) noexcept(false)
{
}

void BookTypes::updateId(const uint64_t id)
{
}

const std::vector<std::string> &BookTypes::insertColumns() noexcept
{
    static const std::vector<std::string> inCols={
    };
    return inCols;
}

void BookTypes::outputArgs(drogon::orm::internal::SqlBinder &binder) const
{
}

const std::vector<std::string> BookTypes::updateColumns() const
{
    std::vector<std::string> ret;
    return ret;
}

void BookTypes::updateArgs(drogon::orm::internal::SqlBinder &binder) const
{
}
Json::Value BookTypes::toJson() const
{
    Json::Value ret;
    return ret;
}

Json::Value BookTypes::toMasqueradedJson(
    const std::vector<std::string> &pMasqueradingVector) const
{
    Json::Value ret;
    if(pMasqueradingVector.size() == 0)
    {
        return ret;
    }
    LOG_ERROR << "Masquerade failed";
    return ret;
}

bool BookTypes::validateJsonForCreation(const Json::Value &pJson, std::string &err)
{
    return true;
}
bool BookTypes::validateMasqueradedJsonForCreation(const Json::Value &pJson,
                                                   const std::vector<std::string> &pMasqueradingVector,
                                                   std::string &err)
{
    if(pMasqueradingVector.size() != 0)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool BookTypes::validateJsonForUpdate(const Json::Value &pJson, std::string &err)
{
    return true;
}
bool BookTypes::validateMasqueradedJsonForUpdate(const Json::Value &pJson,
                                                 const std::vector<std::string> &pMasqueradingVector,
                                                 std::string &err)
{
    if(pMasqueradingVector.size() != 0)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool BookTypes::validJsonOfField(size_t index,
                                 const std::string &fieldName,
                                 const Json::Value &pJson,
                                 std::string &err,
                                 bool isForCreation)
{
    switch(index)
    {
        default:
            err="Internal error in the server";
            return false;
    }
    return true;
}
