/**
 *
 *  Books.cc
 *  DO NOT EDIT. This file is generated by drogon_ctl
 *
 */

#include "Books.h"
#include <drogon/utils/Utilities.h>
#include <string>

using namespace drogon;
using namespace drogon::orm;
using namespace drogon_model::library;

const std::string Books::primaryKeyName = "book_num";
const bool Books::hasPrimaryKey = true;
const std::string Books::tableName = "\"books\"";

const std::vector<typename Books::MetaData> Books::metaData_={
};
const std::string &Books::getColumnName(size_t index) noexcept(false)
{
    assert(index < metaData_.size());
    return metaData_[index].colName_;
}
Books::Books(const Row &r, const ssize_t indexOffset) noexcept
{
    if(indexOffset < 0)
    {
    }
    else
    {
        size_t offset = (size_t)indexOffset;
        if(offset + 0 > r.size())
        {
            LOG_FATAL << "Invalid SQL result for this model";
            return;
        }
        size_t index;
    }

}

Books::Books(const Json::Value &pJson, const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 0)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
}

Books::Books(const Json::Value &pJson) noexcept(false)
{
}

void Books::updateByMasqueradedJson(const Json::Value &pJson,
                                            const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 0)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
}

void Books::updateByJson(const Json::Value &pJson) noexcept(false)
{
}

void Books::updateId(const uint64_t id)
{
}

const std::vector<std::string> &Books::insertColumns() noexcept
{
    static const std::vector<std::string> inCols={
    };
    return inCols;
}

void Books::outputArgs(drogon::orm::internal::SqlBinder &binder) const
{
}

const std::vector<std::string> Books::updateColumns() const
{
    std::vector<std::string> ret;
    return ret;
}

void Books::updateArgs(drogon::orm::internal::SqlBinder &binder) const
{
}
Json::Value Books::toJson() const
{
    Json::Value ret;
    return ret;
}

Json::Value Books::toMasqueradedJson(
    const std::vector<std::string> &pMasqueradingVector) const
{
    Json::Value ret;
    if(pMasqueradingVector.size() == 0)
    {
        return ret;
    }
    LOG_ERROR << "Masquerade failed";
    return ret;
}

bool Books::validateJsonForCreation(const Json::Value &pJson, std::string &err)
{
    return true;
}
bool Books::validateMasqueradedJsonForCreation(const Json::Value &pJson,
                                               const std::vector<std::string> &pMasqueradingVector,
                                               std::string &err)
{
    if(pMasqueradingVector.size() != 0)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool Books::validateJsonForUpdate(const Json::Value &pJson, std::string &err)
{
    return true;
}
bool Books::validateMasqueradedJsonForUpdate(const Json::Value &pJson,
                                             const std::vector<std::string> &pMasqueradingVector,
                                             std::string &err)
{
    if(pMasqueradingVector.size() != 0)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool Books::validJsonOfField(size_t index,
                             const std::string &fieldName,
                             const Json::Value &pJson,
                             std::string &err,
                             bool isForCreation)
{
    switch(index)
    {
        default:
            err="Internal error in the server";
            return false;
    }
    return true;
}
