/**
 *
 *  BooksInUse.h
 *  DO NOT EDIT. This file is generated by drogon_ctl
 *
 */

#pragma once
#include <drogon/orm/Result.h>
#include <drogon/orm/Row.h>
#include <drogon/orm/Field.h>
#include <drogon/orm/SqlBinder.h>
#include <drogon/orm/Mapper.h>
#include <drogon/orm/BaseBuilder.h>
#ifdef __cpp_impl_coroutine
#include <drogon/orm/CoroMapper.h>
#endif
#include <trantor/utils/Date.h>
#include <trantor/utils/Logger.h>
#include <json/json.h>
#include <string>
#include <string_view>
#include <memory>
#include <vector>
#include <tuple>
#include <stdint.h>
#include <iostream>

namespace drogon
{
namespace orm
{
class DbClient;
using DbClientPtr = std::shared_ptr<DbClient>;
}
}
namespace drogon_model
{
namespace library
{

class BooksInUse
{
  public:
    struct Cols
    {
        static const std::string _book_in_use_num;
        static const std::string _reader_num;
        static const std::string _book_num;
        static const std::string _issue_date;
        static const std::string _return_date;
        static const std::string _return_period;
    };

    static const int primaryKeyNumber;
    static const std::string tableName;
    static const bool hasPrimaryKey;
    static const std::string primaryKeyName;
    using PrimaryKeyType = int32_t;
    const PrimaryKeyType &getPrimaryKey() const;

    /**
     * @brief constructor
     * @param r One row of records in the SQL query result.
     * @param indexOffset Set the offset to -1 to access all columns by column names,
     * otherwise access all columns by offsets.
     * @note If the SQL is not a style of 'select * from table_name ...' (select all
     * columns by an asterisk), please set the offset to -1.
     */
    explicit BooksInUse(const drogon::orm::Row &r, const ssize_t indexOffset = 0) noexcept;

    /**
     * @brief constructor
     * @param pJson The json object to construct a new instance.
     */
    explicit BooksInUse(const Json::Value &pJson) noexcept(false);

    /**
     * @brief constructor
     * @param pJson The json object to construct a new instance.
     * @param pMasqueradingVector The aliases of table columns.
     */
    BooksInUse(const Json::Value &pJson, const std::vector<std::string> &pMasqueradingVector) noexcept(false);

    BooksInUse() = default;

    void updateByJson(const Json::Value &pJson) noexcept(false);
    void updateByMasqueradedJson(const Json::Value &pJson,
                                 const std::vector<std::string> &pMasqueradingVector) noexcept(false);
    static bool validateJsonForCreation(const Json::Value &pJson, std::string &err);
    static bool validateMasqueradedJsonForCreation(const Json::Value &,
                                                const std::vector<std::string> &pMasqueradingVector,
                                                    std::string &err);
    static bool validateJsonForUpdate(const Json::Value &pJson, std::string &err);
    static bool validateMasqueradedJsonForUpdate(const Json::Value &,
                                          const std::vector<std::string> &pMasqueradingVector,
                                          std::string &err);
    static bool validJsonOfField(size_t index,
                          const std::string &fieldName,
                          const Json::Value &pJson,
                          std::string &err,
                          bool isForCreation);

    /**  For column book_in_use_num  */
    ///Get the value of the column book_in_use_num, returns the default value if the column is null
    const int32_t &getValueOfBookInUseNum() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<int32_t> &getBookInUseNum() const noexcept;
    ///Set the value of the column book_in_use_num
    void setBookInUseNum(const int32_t &pBookInUseNum) noexcept;

    /**  For column reader_num  */
    ///Get the value of the column reader_num, returns the default value if the column is null
    const int32_t &getValueOfReaderNum() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<int32_t> &getReaderNum() const noexcept;
    ///Set the value of the column reader_num
    void setReaderNum(const int32_t &pReaderNum) noexcept;
    void setReaderNumToNull() noexcept;

    /**  For column book_num  */
    ///Get the value of the column book_num, returns the default value if the column is null
    const int32_t &getValueOfBookNum() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<int32_t> &getBookNum() const noexcept;
    ///Set the value of the column book_num
    void setBookNum(const int32_t &pBookNum) noexcept;
    void setBookNumToNull() noexcept;

    /**  For column issue_date  */
    ///Get the value of the column issue_date, returns the default value if the column is null
    const ::trantor::Date &getValueOfIssueDate() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<::trantor::Date> &getIssueDate() const noexcept;
    ///Set the value of the column issue_date
    void setIssueDate(const ::trantor::Date &pIssueDate) noexcept;
    void setIssueDateToNull() noexcept;

    /**  For column return_date  */
    ///Get the value of the column return_date, returns the default value if the column is null
    const ::trantor::Date &getValueOfReturnDate() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<::trantor::Date> &getReturnDate() const noexcept;
    ///Set the value of the column return_date
    void setReturnDate(const ::trantor::Date &pReturnDate) noexcept;
    void setReturnDateToNull() noexcept;

    /**  For column return_period  */
    ///Get the value of the column return_period, returns the default value if the column is null
    const int32_t &getValueOfReturnPeriod() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<int32_t> &getReturnPeriod() const noexcept;
    ///Set the value of the column return_period
    void setReturnPeriod(const int32_t &pReturnPeriod) noexcept;


    static size_t getColumnNumber() noexcept {  return 6;  }
    static const std::string &getColumnName(size_t index) noexcept(false);

    Json::Value toJson() const;
    Json::Value toMasqueradedJson(const std::vector<std::string> &pMasqueradingVector) const;
    /// Relationship interfaces
  private:
    friend drogon::orm::Mapper<BooksInUse>;
    friend drogon::orm::BaseBuilder<BooksInUse, true, true>;
    friend drogon::orm::BaseBuilder<BooksInUse, true, false>;
    friend drogon::orm::BaseBuilder<BooksInUse, false, true>;
    friend drogon::orm::BaseBuilder<BooksInUse, false, false>;
#ifdef __cpp_impl_coroutine
    friend drogon::orm::CoroMapper<BooksInUse>;
#endif
    static const std::vector<std::string> &insertColumns() noexcept;
    void outputArgs(drogon::orm::internal::SqlBinder &binder) const;
    const std::vector<std::string> updateColumns() const;
    void updateArgs(drogon::orm::internal::SqlBinder &binder) const;
    ///For mysql or sqlite3
    void updateId(const uint64_t id);
    std::shared_ptr<int32_t> bookInUseNum_;
    std::shared_ptr<int32_t> readerNum_;
    std::shared_ptr<int32_t> bookNum_;
    std::shared_ptr<::trantor::Date> issueDate_;
    std::shared_ptr<::trantor::Date> returnDate_;
    std::shared_ptr<int32_t> returnPeriod_;
    struct MetaData
    {
        const std::string colName_;
        const std::string colType_;
        const std::string colDatabaseType_;
        const ssize_t colLength_;
        const bool isAutoVal_;
        const bool isPrimaryKey_;
        const bool notNull_;
    };
    static const std::vector<MetaData> metaData_;
    bool dirtyFlag_[6]={ false };
  public:
    static const std::string &sqlForFindingByPrimaryKey()
    {
        static const std::string sql="select * from " + tableName + " where book_in_use_num = $1";
        return sql;
    }

    static const std::string &sqlForDeletingByPrimaryKey()
    {
        static const std::string sql="delete from " + tableName + " where book_in_use_num = $1";
        return sql;
    }
    std::string sqlForInserting(bool &needSelection) const
    {
        std::string sql="insert into " + tableName + " (";
        size_t parametersCount = 0;
        needSelection = false;
            sql += "book_in_use_num,";
            ++parametersCount;
        if(dirtyFlag_[1])
        {
            sql += "reader_num,";
            ++parametersCount;
        }
        if(dirtyFlag_[2])
        {
            sql += "book_num,";
            ++parametersCount;
        }
        if(dirtyFlag_[3])
        {
            sql += "issue_date,";
            ++parametersCount;
        }
        if(dirtyFlag_[4])
        {
            sql += "return_date,";
            ++parametersCount;
        }
        sql += "return_period,";
        ++parametersCount;
        if(!dirtyFlag_[5])
        {
            needSelection=true;
        }
        needSelection=true;
        if(parametersCount > 0)
        {
            sql[sql.length()-1]=')';
            sql += " values (";
        }
        else
            sql += ") values (";

        int placeholder=1;
        char placeholderStr[64];
        size_t n=0;
        sql +="default,";
        if(dirtyFlag_[1])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[2])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[3])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[4])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[5])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        else
        {
            sql +="default,";
        }
        if(parametersCount > 0)
        {
            sql.resize(sql.length() - 1);
        }
        if(needSelection)
        {
            sql.append(") returning *");
        }
        else
        {
            sql.append(1, ')');
        }
        LOG_TRACE << sql;
        return sql;
    }
};
} // namespace library
} // namespace drogon_model
